/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.deser;


/**<p>Description:hashmap解码子</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/

import java.util.HashMap;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;


public class HashMapDeserializer extends DeserializerImpl {
	/**
	 * @see org.xml.sax.ContentHandler#endElement(java.lang.String, java.lang.String, java.lang.String)
	 */
	public void endElement(String namespaceURI, String localName, String qName,DeserializationContext ctx)
		throws SAXException {
		getTarget().setValue(value);
	}

	/**
	 * @see org.xml.sax.ContentHandler#startElement(java.lang.String, java.lang.String, java.lang.String, org.xml.sax.Attributes)
	 */
	public void startElement(
		String namespaceURI,
		String localName,
		String qName,
		Attributes attrs)
		throws SAXException {
		HashMap item = new HashMap();
		String paraName = null;
		for (int i = 0; i < attrs.getLength(); i++) {
			paraName = attrs.getQName(i);
			item.put(paraName, attrs.getValue(paraName));
		}
		value = item;

	}

	/**
	 * @see org.radf.plat.soap.encoding.SOAPHandler#endChild(java.lang.String, java.lang.String)
	 */
	public void endChild(String s, String s1) throws SAXException {

	}

	/**
	 * @see org.radf.plat.soap.encoding.SOAPHandler#endElement(java.lang.String, java.lang.String)
	 */
	public void endElement(String namespace, String localName)
		throws SAXException {

	}

	/**
	 * 处理子标签
	 * @see org.radf.plat.soap.encoding.SOAPHandler#startChild(java.lang.String, java.lang.String, java.lang.String, org.xml.sax.Attributes)
	 */
	public SOAPHandler startChild(
		String namespace,
		String localName,
		String prefix,
		Attributes attributes,
		DeserializationContext ctx)
		throws SAXException {

		Deserializer deser = ctx.getDeserializer(localName);
		deser.registTarget(this);

		return (SOAPHandler) deser;
	}
	/**
	 * @see org.radf.plat.soap.encoding.Deserializer#setValue(java.lang.
	 * String,java. lang. Object)
	 */
	public void setValue(String key, Object val) {
		((HashMap) value).put(key, val);
	}

}
