/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.deser;

/**<p>Description:解码子接口</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/

public interface Deserializer {
    void deserialize();
    void setValue(Object value);
    void registTarget(Deserializer deseria);
	public void setValue(String key,Object value);
}
