/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.ser;

/**<p>Description:hashmap±àÂë×Ó</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map.Entry;

public class HashMapSerializer implements Serializer {
	private static final String END_TAG = "/>";
	private static final String START_TAG = "<row ";
	/**
	 * @see org.radf.plat.soap.encoding.Serializer#serialize(java.lang.StringBuffer, java.lang.Object, org.radf.plat.soap.encoding.SerializationContext)
	 */
	public void serialize(
		String Qname,
		StringBuffer out,
		Object value,
		SerializationContext ctx) {
		HashMap map = (HashMap) value;
		//startElement
		out.append(START_TAG);
		for (Iterator i = map.entrySet().iterator(); i.hasNext();) {
			Entry entry = (Entry) i.next();
			String key = (String) entry.getKey();
			Object val = entry.getValue();
			ctx.serialize(key, out, val);

		}
		//endElement
		out.append(END_TAG);
	}

}
