/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.ser;

/**<p>Description:±àÂë×Ó½Ó¿Ú</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/
public interface Serializer {
    void serialize(String Qname,StringBuffer out,Object value,SerializationContext ctx);
}
