/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.ser;

/**<p>Description:soap消息编码上下文接口</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/

public interface SerializationContext {
    void serialize(String Qname,
	StringBuffer out,
	Object value);
	void init();
}
