/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.ser;

/**
 * <p>Description:vector±àÂë×Ó</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/

import java.util.Iterator;
import java.util.Vector;

public class VectorSerializer implements Serializer {
	/**
	 * @see org.radf.plat.soap.encoding.Serializer#serialize(java.lang.StringBuffer, java.lang.Object, org.radf.plat.soap.encoding.SerializationContext)
	 */
	public void serialize(
		String Qname,
		StringBuffer out,
		Object value,
		SerializationContext ctx) {
		startElement(Qname, out);
		Vector vector = (Vector) value;
		Iterator iter = vector.iterator();

		while (iter.hasNext()) {

			ctx.serialize(null, out, iter.next());
		}
		endElement(out);
	}
	private void endElement(StringBuffer out) {
		out.append("</resultset>");
	}
	private void startElement(String Qname, StringBuffer out) {
		out.append("<resultset name=\"");
		out.append(Qname);
		out.append("\">");
	}

}
