/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.deser;

/**<p>Description:½âÂë×Ó¸¸Àà</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;



public class DeserializerImpl extends SOAPHandler implements Deserializer {
	/**
	 * @see org.radf.plat.soap.encoding.Deserializer#deserialize()
	 */
	public void deserialize() {
	}
	
	private Deserializer target;
	protected Object value;

	/**
	 * @see org.xml.sax.ContentHandler#endDocument()
	 */
	public void endDocument() throws SAXException {
		super.endDocument();
	}

	/**
	 * @see org.xml.sax.ContentHandler#endElement(java.lang.String, java.lang.String, java.lang.String)
	 */
	public void endElement(String namespaceURI, String localName, String qName)
		throws SAXException {
		super.endElement(namespaceURI, localName, qName);
	}

	/**
	 * @see org.xml.sax.ContentHandler#startDocument()
	 */
	public void startDocument() throws SAXException {
		super.startDocument();
	}

	/**
	 * @see org.xml.sax.ContentHandler#startElement(java.lang.String, java.lang.String, java.lang.String, org.xml.sax.Attributes)
	 */
	public void startElement(
		String namespaceURI,
		String localName,
		String qName,
		Attributes atts)
		throws SAXException {
		super.startElement(namespaceURI, localName, qName, atts);
	}
	
	public void setValue(Object value)
	{
		
	}
	public void setValue(String key,Object value)
	{
	}
	

	/**
	 * @see org.radf.plat.soap.encoding.Deserializer#registTarget(org.radf.plat.soap.encoding.Deserializer)
	 */
	public void registTarget(Deserializer deser) {
		
		target=deser;
	}

	/**
	 * Returns the target.
	 * @return Deserializer
	 */
	public Deserializer getTarget() {
		return target;
	}


}
