/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.deser;


/**<p>Description:½Ó¿Ú</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/

import org.radf.plat.util.exception.WebException;

public interface DeserializationContext {
    
	public Deserializer getDeserializer(String qName);
	public void setValue(Object value);
	public Object getValue();
	public void deserialize(String xmlString) throws WebException;
	public void init();
    
}
