/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.deser;


/**<p>Description:soap消息qname映射管理类</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/

import java.util.HashMap;


public class QnameMappings {
	private HashMap maps;
	/**
	 * 获得解码子.
	 * @param value
	 * @return Serializer
	 */
	public Deserializer getDeserializer(String key) {

		return (Deserializer) maps.get(key);
	}
	/**
	 * 初始化.
	 */
	public void init() {
		//creator all Serializer
		maps = new HashMap();
		maps.put("in:business", new EventDeserializer());
		maps.put("row", new HashMapDeserializer());
		maps.put("para", new StringDeserializer());
		maps.put("paralist", new VectorDeserializer());

	}
}
