/* Generated by Together */

package org.radf.plat.sieaf.soap.encoding.ser;

/**
 * <p>Description:soap消息编码，该类提供一个上下文环境
 * 控制编码的过程</p>
 * <p>Copyright: Copyright (c) 2002 by LBS Co., Ltd.</p>
 * <p>Company: LBS</p>
 * @author chenshuichao
 * @version 1.0
*/
//import java.util.HashMap;
//import java.util.Vector;
//
//import org.radf.plat.event.EventResponse;

public class SerializationContextImpl implements SerializationContext {
	/**
     * Method init.
     */
    public void init() {
        this.mappings = new TypeMappings();
        mappings.init();
    }

    /**
     * @see org.radf.plat.soap.encoding.serializationContext#serialize()
     */
    public void serialize(String Qname, StringBuffer out, Object value) {
        Serializer serializer = mappings.getSerializer(value);
        serializer.serialize(Qname, out, value, this);
    }

    private TypeMappings mappings;
}
